FROM golang:1.13
MAINTAINER Arve Knudsen <arve.knudsen@gmail.com>

# Build container to have a consistent go build environment

COPY . /go/src/probe
WORKDIR /go/src/probe

RUN go get ./... \
    && CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-w -s' -o /target/probe .
